# Generated by Django 4.2.6 on 2023-10-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
    ]
