# Generated by Django 4.2.6 on 2023-10-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosCategorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'productos_categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductosProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'productos_productos',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'managed': False},
        ),
    ]
