# Generated by Django 4.2.6 on 2023-10-27 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productoscategorias_productosproductos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductosCategorias',
        ),
        migrations.DeleteModel(
            name='ProductosProductos',
        ),
        migrations.AlterModelTable(
            name='categorias',
            table='categorias',
        ),
        migrations.AlterModelTable(
            name='productos',
            table='productos',
        ),
    ]
